-- -- Retrieve all records from the e-commerce dataset for initial data exploration
SELECT * FROM Ecommerce_sales_data

-- Filter delivered and shipped orders and sort by total revenue in ascending order
SELECT ORDERID,PRODUCT, REFERRAL_SOURCE, UNIT_PRICE, Quantity, TOTAL_PRICE FROM Ecommerce_sales_data
WHERE Order_Status = 'DELIVERED' OR Order_Status = 'SHIPPED'
ORDER BY Total_Price ASC;

-- Distribution of orders across different order statuses 
SELECT Order_Status,
       COUNT(*) AS TOTAL_Order 
FROM Ecommerce_sales_data
GROUP BY Order_Status
ORDER BY TOTAL_ORDER ASC;

-- Total number of successfully delivered orders
SELECT 'Delivered order' As Order_Status,
COUNT(*) AS Total_Order
FROM Ecommerce_sales_data
WHERE Order_Status = 'DELIVERED'

-- Overall revenue generated from all orders
SELECT SUM(Total_Price) AS Total_Revenue
FROM Ecommerce_sales_data;

-- Average order value across all transactions
SELECT avg(Total_Price) AS Average_Revenue
FROM Ecommerce_sales_data;

-- Highest single order value recorded in the dataset
SELECT MAX(Total_Price) AS Highest_Revenue
FROM Ecommerce_sales_data;

-- Lowest single order value recorded in the dataset
SELECT MIN(Total_Price) AS Lowest_Revenue
FROM Ecommerce_sales_data;

-- Revenue range (highest and lowest order value) by product category
SELECT product,
       MAX(total_price) AS highest_Revenue,
       MIN(total_price) AS lowest_Revenue
FROM Ecommerce_sales_data
GROUP BY product;

-- Number of orders per product category
SELECT Product,
       COUNT(OrderID) AS Total_Order
FROM Ecommerce_sales_data
GROUP BY Product
ORDER BY Total_Order DESC;

-- Total revenue generated by each product category
SELECT Product,
       SUM(Total_Price) AS Total_Revenue
FROM Ecommerce_sales_data
GROUP BY Product
ORDER BY Total_Revenue DESC;

-- Revenue contribution based on order status
SELECT Order_Status,
       SUM(Total_Price) AS Total_Revenue
FROM Ecommerce_sales_data
GROUP BY Order_Status
ORDER BY Total_Revenue ASC;

-- Number of orders generated from each payment method
SELECT Payment_Method,
       COUNT(OrderID) AS Total_Order
FROM Ecommerce_sales_data
GROUP BY Payment_Method
ORDER BY Total_Order DESC;

-- Revenue breakdown by payment method
SELECT Payment_Method,
       SUM(Total_Price) AS Total_Revenue
FROM Ecommerce_sales_data
GROUP BY Payment_Method
ORDER BY Total_Revenue DESC;

-- Number of orders generated from each referral source
SELECT Referral_Source,
       COUNT(OrderID) AS Total_Order
FROM Ecommerce_sales_data
GROUP BY Referral_Source
ORDER BY Total_Order DESC;

-- Revenue contribution by referral source
SELECT Referral_Source,
       SUM(Total_Price) AS Total_Revenue
FROM Ecommerce_sales_data
GROUP BY Referral_Source
ORDER BY Total_Revenue DESC;

-- Order frequency based on coupon usage
SELECT Coupon_Code,
       COUNT(OrderID) AS Total_Order
FROM Ecommerce_sales_data
GROUP BY Coupon_Code
ORDER BY Total_Order ASC;

-- Total revenue from orders where no coupon was used
SELECT 'No Coupon' AS Coupon_code,
SUM(Total_Price) AS Total_Revenue
FROM Ecommerce_sales_data
WHERE Coupon_Code = 'NO COUPON';
